### ISSUE TITLE
Add more GraphQL Adopters

### ISSUE THREAD

**Issue by caniszczyk** [graphql/graphql-landscape#6]
https://graphql.org/users/

Atlassian
FB
GitHub
Hasura
Intuit
neo4j
Paypal
Pinterest
Shopify
Yelp
Wayfair

**Comment by caniszczyk** [comment]
cc: @amye

**Comment by dshaw** [comment]
Taking an action to add PayPal.

**Comment by caniszczyk** [comment]
thanks @dshaw
